### ISSUE TITLE
Wrong usage of mutex

### ISSUE THREAD

**Issue by soupdiver** [cloudradar-monitoring/frontman#34]
Looking through the code I found the following: https://github.com/cloudradar-monitoring/frontman/blob/master/handler.go#L200

I don't think it makes much sense to create and use the `sync.Mutex` inside the function.
A mutex is used to synchronise  concurrent access to resources.
Therefor the mutex should be a property of `Frontman` so we make sure there is only one mutex that control access. Otherwise multiple goroutines would simply create their own mutex and the access across them is not synchronised.

**Comment by requilence** [comment]
You are right. Of course, no need in Mutex here. Don't know why I put it there. I made the PR #44
